# Logistic Regression tutorial

In [123]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import pickle

## Read the data

In [4]:
raw_data = pd.read_csv('population_par_wilaya.csv')

In [9]:
raw_data.head()

wilaya_id          wilaya   pop_0_4_ans  pop_5_9_ans  pop_10_14_ans  \
0          1           ADRAR   47853.94794  43604.17006    45558.73708   
1          2           CHLEF   99479.06821  86435.77046    99844.36111   
2          3        LAGHOUAT   54707.88632  49268.41397    49013.76574   
3          4  OUM EL BOUAGHI   64170.61506  52110.80382    62099.34408   
4          5           BATNA  113327.32220  98755.67713   115804.96540   

   pop_15_19_ans  pop_20_24_ans  pop_25_29_ans  pop_30_34_ans  pop_35_39_ans  \
0    47761.00471    46997.36342    39739.12750    24704.37392    21745.78801   
1   117865.23220   123945.72600   104558.96420    78304.80207    62422.72551   
2    50202.78644    47906.17408    43555.13561    33528.08208    29715.29456   
3    71744.37465    72270.28480    61742.72330    46627.44867    37405.42570   
4   132083.38180   129136.13590   107337.72570    84384.77341    68764.22777   

   ...  geole_rou_geole  lose_brucel_lose  hepatite_virale_a  \
0  ...               59                 7                  1   
1  ...               13                 1                 16   
2  ...                3               185                  0   
3  ...                3               228                 24   
4  ...               31                63                 38   

   hepatite_virale_b  hepatite_virale_c  coque_luche  dysen_terie  typh-oide  \
0                 85                 11            0          161         16   
1                  6                  3            0            4          3   
2                  0                  0            0            7         55   
3                 24                 69            0            0         15   
4                 40                 45            2            0          4   

   leishmaniose_cutanee  menin_gite  
0                     2          23  
1                     6          60  
2                   292           7  
3                     4          50  
4                  1015          77  

[5 rows x 61 columns]

In [10]:
raw_data.describe()

wilaya_id   pop_0_4_ans   pop_5_9_ans  pop_10_14_ans  pop_15_19_ans  \
count   49.000000  4.900000e+01  4.900000e+01   4.900000e+01   4.900000e+01   
mean    28.346939  1.389564e+05  1.178748e+05   1.329929e+05   1.483549e+05   
std     30.283075  4.783429e+05  4.056089e+05   4.575232e+05   5.103526e+05   
min      1.000000  6.165500e+03  5.094317e+03   5.085549e+03   5.107578e+03   
25%     13.000000  4.232342e+04  3.646467e+04   4.053335e+04   4.429360e+04   
50%     25.000000  6.637570e+04  5.993406e+04   6.809855e+04   7.658358e+04   
75%     37.000000  8.579150e+04  7.297303e+04   8.392290e+04   9.646350e+04   
max    213.000000  3.404431e+06  2.887934e+06   3.258327e+06   3.634694e+06   

       pop_20_24_ans  pop_25_29_ans  pop_30_34_ans  pop_35_39_ans  \
count   4.900000e+01   4.900000e+01   4.900000e+01   4.900000e+01   
mean    1.535921e+05   1.396699e+05   1.118612e+05   9.560764e+04   
std     5.284522e+05   4.807686e+05   3.854301e+05   3.297478e+05   
min     5.060771e+03   4.960220e+03   3.923482e+03   3.312367e+03   
25%     4.699736e+04   4.355514e+04   3.352808e+04   2.971529e+04   
50%     7.748412e+04   6.496500e+04   5.308496e+04   4.561713e+04   
75%     9.953428e+04   9.154196e+04   7.416484e+04   6.230553e+04   
max     3.763007e+06   3.421914e+06   2.740600e+06   2.342387e+06   

       pop_40_44_ans  ...  geole_rou_geole  lose_brucel_lose  \
count   4.900000e+01  ...        49.000000         49.000000   
mean    8.236852e+04  ...        63.142857        206.367347   
std     2.842045e+05  ...       223.029239        741.279656   
min     2.722098e+03  ...         0.000000          0.000000   
25%     2.606996e+04  ...         3.000000          3.000000   
50%     3.937745e+04  ...        13.000000         17.000000   
75%     4.849781e+04  ...        31.000000        112.000000   
max     2.018029e+06  ...      1547.000000       5056.000000   

       hepatite_virale_a  hepatite_virale_b  hepatite_virale_c  coque_luche  \
count          49.000000          49.000000          49.000000    49.000000   
mean           32.571429          73.551020          38.408163     3.183673   
std           113.197099         255.520063         137.789229    12.296127   
min             0.000000           0.000000           0.000000     0.000000   
25%             3.000000          12.000000           3.000000     0.000000   
50%            11.000000          27.000000           8.000000     0.000000   
75%            24.000000          46.000000          15.000000     0.000000   
max           798.000000        1802.000000         941.000000    78.000000   

       dysen_terie   typh-oide  leishmaniose_cutanee   menin_gite  
count    49.000000   49.000000             49.000000    49.000000  
mean     46.204082   32.897959            311.510204   156.734694  
std     162.970726  116.816495           1139.838149   549.657726  
min       0.000000    0.000000              0.000000     2.000000  
25%       0.000000    3.000000              3.000000    22.000000  
50%       2.000000    6.000000             12.000000    63.000000  
75%      51.000000   15.000000             92.000000    92.000000  
max    1132.000000  806.000000           7632.000000  3840.000000  

[8 rows x 60 columns]

In [12]:
raw_data.columns.values

array(['wilaya_id', 'wilaya', 'pop_0_4_ans', 'pop_5_9_ans',
       'pop_10_14_ans', 'pop_15_19_ans', 'pop_20_24_ans', 'pop_25_29_ans',
       'pop_30_34_ans', 'pop_35_39_ans', 'pop_40_44_ans', 'pop_45_49_ans',
       'pop_50_54_ans', 'pop_55_59_ans', 'pop_60_64_ans', 'pop_65_69_ans',
       'pop_70_74_ans', 'pop_75_79_ans', 'pop_80_84_ans',
       'pop_sup_84_ans', 'pop_nd', 'masculin', 'feminin', 'rural_2008',
       'urbain_2008', 'acl', 'as', 'epars', 'habitant_par_km2_1998',
       'pop_total', 'taux_accroissement_urbain',
       'taux_accroissement_rural', 'taux_accroissement_total', 'retraite',
       'pensionne', 'specialite_homme', 'specialite_femme',
       'generaliste_homme', 'generaliste_femme', 'chir_dentiste_homme',
       'chir_dentiste_femme', 'pharmacien_homme', 'pharmacien_femme',
       'structure_hospitalisation', 'salle_consultation_et_soins',
       'centre_sante', 'polyclinique', 'lits_techniques_2006',
       'lits_organises_2006', 'tracho_me', 'kyste_hydatique'

In [14]:
df = raw_data.copy()

In [16]:
df = df.drop(['wilaya_id', 'wilaya', 'pop_0_4_ans', 'pop_5_9_ans',
       'pop_10_14_ans', 'pop_15_19_ans', 'pop_20_24_ans', 'pop_25_29_ans',
       'pop_30_34_ans', 'pop_35_39_ans', 'pop_40_44_ans', 'pop_45_49_ans',
       'pop_50_54_ans', 'pop_55_59_ans', 'pop_60_64_ans', 'pop_65_69_ans',
       'pop_70_74_ans', 'pop_75_79_ans', 'pop_80_84_ans',
       'pop_sup_84_ans', 'pop_nd', 'acl', 'as', 'epars', 'habitant_par_km2_1998',
        'taux_accroissement_urbain',
       'taux_accroissement_rural', 'taux_accroissement_total', 'retraite',
       'pensionne', 'specialite_homme', 'specialite_femme',
       'generaliste_homme', 'generaliste_femme', 'chir_dentiste_homme',
       'chir_dentiste_femme', 'pharmacien_homme', 'pharmacien_femme',
       'structure_hospitalisation', 'salle_consultation_et_soins',
       'centre_sante', 'polyclinique', 'lits_techniques_2006',
       'lits_organises_2006', 'tracho_me', 'kyste_hydatique',
       'geole_rou_geole', 'lose_brucel_lose', 'hepatite_virale_a',
       'hepatite_virale_b', 'hepatite_virale_c', 'coque_luche',
       'dysen_terie', 'typh-oide', 'leishmaniose_cutanee'], axis = 1)

In [19]:
df.head()

masculin      feminin  rural_2008  urbain_2008     pop_total  menin_gite
0  203836.3422  195877.5045      253856       145858  3.997138e+05          23
1  502469.9090  499617.9663      503567       498521  1.002088e+06          60
2  232657.6061  223209.9158      141353       314248  4.558675e+05           7
3  314084.2888  307527.2184      166892       454720  6.216115e+05          50
4  565240.5826  554389.5847      434792       684999  1.119630e+06          77

## Simplification de la colonne à inférer

In [60]:
df.describe()

masculin       feminin    rural_2008   urbain_2008     pop_total  \
count  4.900000e+01  4.900000e+01  4.900000e+01  4.900000e+01  4.900000e+01   
mean   7.032707e+05  6.875420e+05  4.738307e+05  9.171910e+05  1.390813e+06   
std    2.421392e+06  2.367471e+06  1.631453e+06  3.170362e+06  4.788858e+06   
min    2.499619e+04  2.408814e+04  3.539000e+03  2.893400e+04  4.914914e+04   
25%    2.039484e+05  2.045082e+05  1.225160e+05  2.632440e+05  4.084567e+05   
50%    3.296031e+05  3.226173e+05  2.312310e+05  4.216280e+05  6.487033e+05   
75%    4.656118e+05  4.469652e+05  3.637890e+05  5.124110e+05  9.125770e+05   
max    1.723013e+07  1.684478e+07  1.160885e+07  2.247118e+07  3.407491e+07   

        menin_gite    targets  
count    49.000000  49.000000  
mean    156.734694   0.510204  
std     549.657726   0.505076  
min       2.000000   0.000000  
25%      22.000000   0.000000  
50%      63.000000   1.000000  
75%      92.000000   1.000000  
max    3840.000000   1.000000

In [32]:
# Choix de la médiane (quantile 0.5) pour balancer les données 
targets = np.where(df['menin_gite'] > df['menin_gite'].quantile(0.5), 0 , 1)
targets

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0])

In [38]:
# Vérification du balancing
targets.sum() / len(targets)

0.5102040816326531

In [40]:
# Ajout des targets au DF
df['targets'] = targets

In [42]:
df.head()

masculin      feminin  rural_2008  urbain_2008     pop_total  \
0  203836.3422  195877.5045      253856       145858  3.997138e+05   
1  502469.9090  499617.9663      503567       498521  1.002088e+06   
2  232657.6061  223209.9158      141353       314248  4.558675e+05   
3  314084.2888  307527.2184      166892       454720  6.216115e+05   
4  565240.5826  554389.5847      434792       684999  1.119630e+06   

   menin_gite  targets  
0          23        1  
1          60        1  
2           7        1  
3          50        1  
4          77        0

In [44]:
df_with_targets = df.drop(['menin_gite'], axis = 1) 

In [45]:
df_with_targets.head()

masculin      feminin  rural_2008  urbain_2008     pop_total  targets
0  203836.3422  195877.5045      253856       145858  3.997138e+05        1
1  502469.9090  499617.9663      503567       498521  1.002088e+06        1
2  232657.6061  223209.9158      141353       314248  4.558675e+05        1
3  314084.2888  307527.2184      166892       454720  6.216115e+05        1
4  565240.5826  554389.5847      434792       684999  1.119630e+06        0

In [46]:
df_with_targets.shape

(49, 6)

# Préparer les inputs pour la regression

In [48]:
# Exclure la dernière colone (à inférer)
unscaled_inputs = df_with_targets.iloc[:, :-1]

In [49]:
unscaled_inputs.head()

masculin      feminin  rural_2008  urbain_2008     pop_total
0  203836.3422  195877.5045      253856       145858  3.997138e+05
1  502469.9090  499617.9663      503567       498521  1.002088e+06
2  232657.6061  223209.9158      141353       314248  4.558675e+05
3  314084.2888  307527.2184      166892       454720  6.216115e+05
4  565240.5826  554389.5847      434792       684999  1.119630e+06

In [53]:
# Création d'un objet scaler
meningite_scaler = StandardScaler()

In [54]:
# Paramèter le scaler
meningite_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [56]:
# Uniformiser l'échele des données 
scaled_inputs = meningite_scaler.transform(unscaled_inputs)

In [59]:
# Vérification du shape
scaled_inputs.shape

(49, 5)

# Diviser les données - train - test  

In [72]:
# division 80%-20%
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8)

In [73]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(39, 5) (10, 5) (39,) (10,)


In [84]:
# Objet Regression
reg = LogisticRegression(solver='lbfgs')

In [85]:
# Construction du modèle
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [87]:
# vérification du score
reg.score(x_train, y_train)

0.7948717948717948

## Vérifier la précision manuellement

In [91]:
# Inférence des résultats
model_outputs = reg.predict(x_train)

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True])

In [93]:
# vérification de la précision
np.sum(model_outputs==y_train) / x_train.shape[0]

0.7948717948717948

## intercept et coefs

In [94]:
reg.intercept_

array([-0.56181305])

In [96]:
reg.coef_

array([[-0.63614076, -0.64333024, -0.6491785 , -0.63234152, -0.63969563]])

In [101]:
colonnes = unscaled_inputs.columns.values

In [103]:
# Création d'un nouveau DF pour stocker le modèle
summary_table = pd.DataFrame(columns = ['colonnes'], data = colonnes)

In [105]:
# Insertion des coeficients
summary_table['Coefs'] = np.transpose(reg.coef_)

In [107]:
summary_table

colonnes     Coefs
0     masculin -0.636141
1      feminin -0.643330
2   rural_2008 -0.649178
3  urbain_2008 -0.632342
4    pop_total -0.639696

In [108]:
summary_table.index = summary_table.index + 1

In [109]:
# Ajout de intercept (biais) à la DF
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [110]:
summary_table = summary_table.sort_index()

In [111]:
summary_table

colonnes     Coefs
0    Intercept -0.561813
1     masculin -0.636141
2      feminin -0.643330
3   rural_2008 -0.649178
4  urbain_2008 -0.632342
5    pop_total -0.639696

## Interpretation des coeficients

In [113]:
# Ajout d'un champ Odds
summary_table['Odds_ratio'] = np.exp(summary_table.Coefs)

In [116]:
# Trie des Odds afin de détecter les coefficients les plus influents
# La variable est inutile Si les coefficents sont proche de 0 ou les Odds proche de 1 
summary_table.sort_values('Odds_ratio', ascending = False)

colonnes     Coefs  Odds_ratio
0    Intercept -0.561813    0.570174
4  urbain_2008 -0.632342    0.531346
1     masculin -0.636141    0.529331
5    pop_total -0.639696    0.527453
2      feminin -0.643330    0.525539
3   rural_2008 -0.649178    0.522475

## Tester le modèle

In [117]:
# Le score sur les données test est toujour inférieur que celui des train data
# Si la différence est importante (10-20%) le modèle overfit
reg.score(x_test, y_test)

0.6

In [118]:
# Overfitting apparament !!
reg.score(x_train, y_train)

0.7948717948717948

In [119]:
predict_proba = reg.predict_proba(x_test)

In [120]:
predict_proba

array([[0.46146791, 0.53853209],
       [0.5267972 , 0.4732028 ],
       [0.53180042, 0.46819958],
       [0.54736196, 0.45263804],
       [0.54037085, 0.45962915],
       [0.56754381, 0.43245619],
       [0.54180453, 0.45819547],
       [0.47916568, 0.52083432],
       [0.51413726, 0.48586274],
       [0.44985098, 0.55014902]])

In [121]:
predict_proba.shape

(10, 2)

In [122]:
predict_proba[:, 1]

array([0.53853209, 0.4732028 , 0.46819958, 0.45263804, 0.45962915,
       0.43245619, 0.45819547, 0.52083432, 0.48586274, 0.55014902])

# Sauvegarde du modèle et du scaler

In [126]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [127]:
with open('scaler', 'wb') as file:
    pickle.dump(meningite_scaler, file)